services:
  - type: web
    name: aihub-backend
    runtime: node
    rootDir: backend
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 24.14.1
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
